### ISSUE TITLE
Error in Generate HTML report

### ISSUE THREAD

**Issue by marchettibruno** [RKMlab/perf#1]
I can input my data file and output  the + _perf.tsv  file. However, when I  try to generate an HTML report using the "-a" command the fallowing message appears. I also tried to use the "-a" with the "test_data" files from the own "perf-master"  folder, and the same message appears.  

Command:
PERF -i test_input.fa -o test_input_perf.tsv -a 

Result:

Generating HTML report. This may take a while..

Traceback (most recent call last):
  File "C:\Users\zehla\Documents\perfmaster\PERF-script.py", line 11, in <module>
    load_entry_point('perf-ssr==0.4.5', 'console_scripts', 'PERF')()
  File "C:\Users\zehla\Documents\perfmaster\PERF\core.py", line 151, in main
    ssr_native(args, length_cutoff=args.min_length)
  File "C:\Users\zehla\Documents\perfmaster\PERF\core.py", line 101, in ssr_native
    fasta_ssrs(args, repeats_info)
  File "C:\Users\zehla\Documents\perfmaster\PERF\rep_utils.py", line 235, in fasta_ssrs
    analyse_fasta(args)
  File "C:\Users\zehla\Documents\perfmaster\PERF\analyse.py", line 205, in analyse_fasta
    writetoHTML(html_report, defaultInfo, repeat_options, 'fasta')
  File "C:\Users\zehla\Documents\perfmaster\PERF\analyse.py", line 31, in writetoHTML
    lodash_js = open('%s/lib/src/lodash.min.js' %(current_dir), 'r').read()
  File "C:\Users\zehla\Documents\perfmaster\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7378: character maps to <undefined>

**Comment by avvaruakshay** [comment]
Hi,
This seems to be a Windows OS specific issue. We are working on resolving it.

**Comment by sakethsaxena** [comment]
Not sure if this is resolved but that looks like the file might be encoded as 'utf-8-sig' or 'latin-1', might be worth it to try reading by iterating over those encodings by setting the `encoding` parameter in the `open()` method.
