### ISSUE TITLE
Error in build_rep_set from rep_utils.py

### ISSUE THREAD

**Issue by Enorya** [RKMlab/perf#2]
Hi, I'm trying to run PERF on a file using this command:
```bash
PERF -i coral-sequences/0_0_coral-sequences.fastq --format fastq -a -u info/repeat_units.txt -s 300
```
but I have the following error:
```bash
Traceback (most recent call last):
  File "/staging/leuven/stg_00026/Softwares/miniconda3/bin/PERF", line 8, in <module>
    sys.exit(main())
  File "/staging/leuven/stg_00026/Softwares/miniconda3/lib/python3.8/site-packages/PERF/core.py", line 146, in main
    ssr_native(args, unit_cutoff=unit_cutoff)
  File "/staging/leuven/stg_00026/Softwares/miniconda3/lib/python3.8/site-packages/PERF/core.py", line 97, in ssr_native
    repeats_info = build_rep_set(repeat_file, unit_cutoff=unit_cutoff)
  File "/staging/leuven/stg_00026/Softwares/miniconda3/lib/python3.8/site-packages/PERF/rep_utils.py", line 112, in build_rep_set
    motif = motif*unit_cutoff[motif_length]
KeyError: 1
```
My repeats_units.txt file looks like this:
```bash
2  10
3  7
4  4
5  4
```
Do you have any idea from where the error is coming?

**Comment by avvaruakshay** [comment]
Hi Enorya. We have fixed this issue and updated the repository with a new version number 0.4.6.
Please install the new version and try running again. Let us know if you have any issue.
